CREATE DATABASE IF NOT EXISTS hacker_news;
USE hacker_news;

CREATE TABLE IF NOT EXISTS stories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    url VARCHAR(255) NOT NULL,
    posted_at DATETIME NOT NULL
);
